/*!
 * jodit-pro - PRO Version of Jodit Editor
 * Author: Chupurnov Valeriy <chupurnov@gmail.com>
 * Version: v4.2.22
 * Url: https://xdsoft.net/jodit/pro/
 * License(s): SEE LICENSE IN LICENSE.md
 */


!function(e,t){if("object"==typeof exports&&"object"==typeof module)module.exports=t();else if("function"==typeof define&&define.amd)define([],t);else{var o=t();for(var i in o)("object"==typeof exports?exports:e)[i]=o[i]}}(self,(function(){return(self.webpackChunkjodit_pro=self.webpackChunkjodit_pro||[]).push([[782],{8132:function(e){e.exports='<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"> <path d="M17,24a4,4,0,0,0,4-4V4a4,4,0,0,0-4-4H7A4,4,0,0,0,3,4V20a4,4,0,0,0,4,4ZM5,20V4A2,2,0,0,1,7,2H17a2,2,0,0,1,2,2V20a2,2,0,0,1-2,2H7A2,2,0,0,1,5,20Z"/> <path d="M8,19h8a1,1,0,0,0,0-2H8a1,1,0,0,0,0,2Z"/> <path d="M11,5h2a1,1,0,0,0,0-2H11a1,1,0,0,0,0,2Z"/> </svg>'},63807:function(e,t,o){"use strict";o.d(t,{G:function(){return a},m:function(){return d}});var i=o(59372),n=o(49382),r=o(91288),u=o(8132),l=o.n(u);r.T.prototype.mobileView={mode:"default"};var a="buttonmobileSView",d="buttonmobileCView";r.T.prototype.controls.mobileView={tooltip:"Mobile View",icon:l(),command:"mobileView",isActive:function(e){return(0,n.m)(e,d)&&"default"!==(0,n.m)(e,d)},isChildActive:function(e,t){var o,r,u=null===(r=null===(o=t.control)||void 0===o?void 0:o.args)||void 0===r?void 0:r[0];return(0,i.k)(u)&&(u=Number(u)),((0,n.m)(e,d)||"default")===u},exec:function(e){if(!(0,n.m)(e,a))return!1;e.execCommand("mobileView",!1,(0,n.m)(e,a))},childExec:function(e,t,o){var n,r,u=null===(r=null===(n=o.button.control)||void 0===n?void 0:n.args)||void 0===r?void 0:r[0];e.execCommand("mobileView",!1,(0,i.k)(u)?Number(u):u)},list:{default:"Default",375:"iPhone SE",414:"iPhone XR",390:"iPhone 12 Pro",393:"Pixel 5",820:"iPad Air"}}},11713:function(e,t,o){"use strict";o.r(t);var i=o(31635),n=o(53557),r=o(71122),u=o(65564),l=o(63807),a=o(25511),d=function(e){function t(){var t=e.apply(this,(0,i.fX)([],(0,i.zs)(arguments),!1))||this;return t.buttons=[{name:"mobileView",group:"state"}],t.__currentMode="default",t}return(0,i.C6)(t,e),t.prototype.afterInit=function(e){var t=this;e.registerCommand("mobileView",{exec:function(o,i,n){t.__currentMode===n&&(n="default"),t.__currentMode=n,(0,r.dataBind)(e,l.m,n),"default"!==t.__currentMode&&(0,r.dataBind)(e,l.G,n),"default"===n?(0,r.css)(t.jodit.workplace,{width:null,margin:null}):(0,r.css)(t.j.workplace,{width:n,margin:"0 auto"})}}),e.events.on("beforeSetMode",(function(){}))},t.prototype.__beforeSetMode=function(){"default"!==this.__currentMode&&this.j.execCommand("mobileView",!1,"default")},t.prototype.beforeDestruct=function(e){},t.requires=["license"],(0,i.Cg)([(0,n.watch)(":beforeSetMode.mobileView")],t.prototype,"__beforeSetMode",null),(0,i.Cg)([n.component],t)}(u.k);a.A.plugins.add("mobileView",d)}},function(e){return e(e.s=11713)}])}));